"""Initial database schema

Revision ID: 0283144cf0fb
Revises: 
Create Date: 2025-09-21 09:59:56.157294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0283144cf0fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localization_strings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('string_key', sa.String(length=100), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('string_value', sa.Text(), nullable=False),
    sa.Column('context', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_localization_key_lang', 'localization_strings', ['string_key', 'language_code'], unique=False)
    op.create_index(op.f('ix_localization_strings_language_code'), 'localization_strings', ['language_code'], unique=False)
    op.create_index(op.f('ix_localization_strings_string_key'), 'localization_strings', ['string_key'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_setting_category', 'system_settings', ['category'], unique=False)
    op.create_index('idx_system_setting_key', 'system_settings', ['setting_key'], unique=False)
    op.create_index(op.f('ix_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('google_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_google_id', 'users', ['google_id'], unique=False)
    op.create_index('idx_user_tier', 'users', ['tier'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_key', sa.String(length=100), nullable=False, unique=True),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_active', 'categories', ['is_active'], unique=False)
    op.create_index('idx_category_system', 'categories', ['is_system'], unique=False)
    op.create_index('idx_category_user_id', 'categories', ['user_id'], unique=False)
    op.create_index('idx_category_reference_key', 'categories', ['reference_key'], unique=True)
    # Create category_translations table
    op.create_table('category_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_trans_category_id', 'category_translations', ['category_id'], unique=False)
    op.create_index('idx_category_trans_lang', 'category_translations', ['language_code'], unique=False)
    op.create_index('idx_category_trans_category_lang', 'category_translations', ['category_id', 'language_code'], unique=True)
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_setting_user_key', 'user_settings', ['user_id', 'setting_key'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('google_drive_file_id', sa.String(length=100), nullable=False),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_drive_file_id')
    )
    op.create_index('idx_document_category_id', 'documents', ['category_id'], unique=False)
    op.create_index('idx_document_google_drive', 'documents', ['google_drive_file_id'], unique=False)
    op.create_index('idx_document_status', 'documents', ['processing_status'], unique=False)
    op.create_index('idx_document_user_id', 'documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_document_user_id', table_name='documents')
    op.drop_index('idx_document_status', table_name='documents')
    op.drop_index('idx_document_google_drive', table_name='documents')
    op.drop_index('idx_document_category_id', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_user_setting_user_key', table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index('idx_category_user_id', table_name='categories')
    op.drop_index('idx_category_system', table_name='categories')
    op.drop_index('idx_category_active', table_name='categories')
    op.drop_index('idx_category_trans_category_lang', table_name='category_translations')
    op.drop_index('idx_category_trans_lang', table_name='category_translations')
    op.drop_index('idx_category_trans_category_id', table_name='category_translations')
    op.drop_table('category_translations')
    op.drop_index('idx_category_reference_key', table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_tier', table_name='users')
    op.drop_index('idx_user_google_id', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_settings_setting_key'), table_name='system_settings')
    op.drop_index('idx_system_setting_key', table_name='system_settings')
    op.drop_index('idx_system_setting_category', table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_localization_strings_string_key'), table_name='localization_strings')
    op.drop_index(op.f('ix_localization_strings_language_code'), table_name='localization_strings')
    op.drop_index('idx_localization_key_lang', table_name='localization_strings')
    op.drop_table('localization_strings')
    # ### end Alembic commands ###