"""Add Russian language support to categories

Revision ID: 9ca3c4514de4
Revises: 5c448b08fbc7
Create Date: 2025-09-21 10:27:28.910355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ca3c4514de4'
down_revision = '5c448b08fbc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name_ru', sa.String(length=100), nullable=False))
    op.add_column('categories', sa.Column('description_ru', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'description_ru')
    op.drop_column('categories', 'name_ru')
    # ### end Alembic commands ###