cat > .github/workflows/deploy.yml << 'EOF'
name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Configure Docker
      run: gcloud auth configure-docker
    
    - name: Build Docker image
      run: |
        cd backend
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/bonifatus-dms:${{ github.sha }} .
    
    - name: Push Docker image
      run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/bonifatus-dms:${{ github.sha }}
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy bonifatus-dms \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/bonifatus-dms:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars="DATABASE_URL=${{ secrets.DATABASE_URL }}" \
          --set-env-vars="GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" \
          --set-env-vars="GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" \
          --set-env-vars="SECURITY_SECRET_KEY=${{ secrets.SECURITY_SECRET_KEY }}" \
          --set-env-vars="APP_ENVIRONMENT=production"
EOF