name: Deploy to Google Cloud Run
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      
      - name: Store service account key in Secret Manager
        run: |
          echo '${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT_KEY }}' | gcloud secrets create bonifatus-drive-service-key --data-file=- --replication-policy=automatic || \
          echo '${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT_KEY }}' | gcloud secrets versions add bonifatus-drive-service-key --data-file=-
      
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev
      
      - name: Build Docker image
        run: |
          cd backend
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/bonifatus-dms/bonifatus-dms:${{ github.sha }} .
      
      - name: Push Docker image
        run: docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/bonifatus-dms/bonifatus-dms:${{ github.sha }}
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy bonifatus-dms \
            --image us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/bonifatus-dms/bonifatus-dms:${{ github.sha }} \
            --platform managed \
            --region